window.env = {
  "ACLOCAL_PATH": "C:\\Program Files\\Git\\mingw64\\share\\aclocal;C:\\Program Files\\Git\\usr\\share\\aclocal",
  "adb": "C:\\Users\\SAFIULLAH\\platform-tools_r30.0.5-windows\\platform-tools\\adb.exe",
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "API_KEY": "63e0e6d4ca41699c72ee23f160202a63",
  "APPDATA": "C:\\Users\\SAFIULLAH\\AppData\\Roaming",
  "APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL": "true",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "132423929310142031",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_14496_WHWRQZNYXWAOGZZY",
  "COLORTERM": "truecolor",
  "COMMONPROGRAMFILES": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-FKHOGE5",
  "COMSPEC": "C:\\WINDOWS\\system32\\cmd.exe",
  "CONFIG_SITE": "C:/Program Files/Git/mingw64/etc/config.site",
  "DISPLAY": "needs-to-be-defined",
  "dmg2img": "C:\\Users\\SAFIULLAH\\Documents\\dmg2img-1.6.2-win32\\dmg2img.exe",
  "dp0": "E:\\Payoneer\\weather-app\\node_modules\\.bin\\",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EXEPATH": "C:\\Program Files\\Git",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\SAFIULLAH\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "GIT_SSH": "C:\\Program Files\\PuTTY\\plink.exe",
  "HOME": "C:\\Users\\SAFIULLAH",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\SAFIULLAH",
  "HOSTNAME": "DESKTOP-FKHOGE5",
  "INFOPATH": "C:\\Program Files\\Git\\usr\\local\\info;C:\\Program Files\\Git\\usr\\share\\info;C:\\Program Files\\Git\\usr\\info;C:\\Program Files\\Git\\share\\info",
  "INIT_CWD": "E:\\Payoneer\\weather-app",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\SAFIULLAH\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-FKHOGE5",
  "MANPATH": "C:\\Program Files\\Git\\mingw64\\local\\man;C:\\Program Files\\Git\\mingw64\\share\\man;C:\\Program Files\\Git\\usr\\local\\man;C:\\Program Files\\Git\\usr\\share\\man;C:\\Program Files\\Git\\usr\\man;C:\\Program Files\\Git\\share\\man",
  "MINGW_CHOST": "x86_64-w64-mingw32",
  "MINGW_PACKAGE_PREFIX": "mingw-w64-x86_64",
  "MINGW_PREFIX": "C:/Program Files/Git/mingw64",
  "MSYSTEM": "MINGW64",
  "MSYSTEM_CARCH": "x86_64",
  "MSYSTEM_CHOST": "x86_64-w64-mingw32",
  "MSYSTEM_PREFIX": "C:/Program Files/Git/mingw64",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_config_access": "",
  "npm_config_allow_same_version": "",
  "npm_config_also": "",
  "npm_config_always_auth": "",
  "npm_config_argv": "{\"remain\":[],\"cooked\":[\"start\"],\"original\":[\"start\"]}",
  "npm_config_audit": "true",
  "npm_config_audit_level": "low",
  "npm_config_auth_type": "legacy",
  "npm_config_before": "",
  "npm_config_bin_links": "true",
  "npm_config_browser": "",
  "npm_config_ca": "",
  "npm_config_cache": "C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm-cache",
  "npm_config_cache_lock_retries": "10",
  "npm_config_cache_lock_stale": "60000",
  "npm_config_cache_lock_wait": "10000",
  "npm_config_cache_max": "Infinity",
  "npm_config_cache_min": "10",
  "npm_config_cafile": "",
  "npm_config_cert": "",
  "npm_config_cidr": "",
  "npm_config_color": "true",
  "npm_config_commit_hooks": "true",
  "npm_config_depth": "Infinity",
  "npm_config_description": "true",
  "npm_config_dev": "",
  "npm_config_dry_run": "",
  "npm_config_editor": "notepad.exe",
  "npm_config_engine_strict": "",
  "npm_config_fetch_retries": "2",
  "npm_config_fetch_retry_factor": "10",
  "npm_config_fetch_retry_maxtimeout": "60000",
  "npm_config_fetch_retry_mintimeout": "10000",
  "npm_config_force": "",
  "npm_config_format_package_lock": "true",
  "npm_config_fund": "true",
  "npm_config_git": "git",
  "npm_config_git_tag_version": "true",
  "npm_config_global": "",
  "npm_config_globalconfig": "C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_globalignorefile": "C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm\\etc\\npmignore",
  "npm_config_global_style": "",
  "npm_config_group": "",
  "npm_config_ham_it_up": "",
  "npm_config_heading": "npm",
  "npm_config_https_proxy": "",
  "npm_config_if_present": "",
  "npm_config_ignore_prepublish": "",
  "npm_config_ignore_scripts": "",
  "npm_config_init_author_email": "",
  "npm_config_init_author_name": "",
  "npm_config_init_author_url": "",
  "npm_config_init_license": "ISC",
  "npm_config_init_module": "C:\\Users\\SAFIULLAH\\.npm-init.js",
  "npm_config_init_version": "1.0.0",
  "npm_config_json": "",
  "npm_config_key": "",
  "npm_config_legacy_bundling": "",
  "npm_config_link": "",
  "npm_config_local_address": "",
  "npm_config_loglevel": "notice",
  "npm_config_logs_max": "10",
  "npm_config_long": "",
  "npm_config_maxsockets": "50",
  "npm_config_message": "%s",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_node_options": "",
  "npm_config_node_version": "12.18.3",
  "npm_config_noproxy": "",
  "npm_config_offline": "",
  "npm_config_onload_script": "",
  "npm_config_only": "",
  "npm_config_optional": "true",
  "npm_config_otp": "",
  "npm_config_package_lock": "true",
  "npm_config_package_lock_only": "",
  "npm_config_parseable": "",
  "npm_config_prefer_offline": "",
  "npm_config_prefer_online": "",
  "npm_config_prefix": "C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm",
  "npm_config_preid": "",
  "npm_config_production": "",
  "npm_config_progress": "true",
  "npm_config_proxy": "",
  "npm_config_read_only": "",
  "npm_config_rebuild_bundle": "true",
  "npm_config_registry": "https://registry.npmjs.org/",
  "npm_config_rollback": "true",
  "npm_config_save": "true",
  "npm_config_save_bundle": "",
  "npm_config_save_dev": "",
  "npm_config_save_exact": "",
  "npm_config_save_optional": "",
  "npm_config_save_prefix": "^",
  "npm_config_save_prod": "",
  "npm_config_scope": "",
  "npm_config_scripts_prepend_node_path": "warn-only",
  "npm_config_script_shell": "",
  "npm_config_searchexclude": "",
  "npm_config_searchlimit": "20",
  "npm_config_searchopts": "",
  "npm_config_searchstaleness": "900",
  "npm_config_send_metrics": "",
  "npm_config_shell": "C:\\WINDOWS\\system32\\cmd.exe",
  "npm_config_shrinkwrap": "true",
  "npm_config_sign_git_commit": "",
  "npm_config_sign_git_tag": "",
  "npm_config_sso_poll_frequency": "500",
  "npm_config_sso_type": "oauth",
  "npm_config_strict_ssl": "true",
  "npm_config_tag": "latest",
  "npm_config_tag_version_prefix": "v",
  "npm_config_timing": "",
  "npm_config_tmp": "C:\\Users\\SAFIUL~1\\AppData\\Local\\Temp",
  "npm_config_umask": "0000",
  "npm_config_unicode": "",
  "npm_config_unsafe_perm": "true",
  "npm_config_update_notifier": "true",
  "npm_config_usage": "",
  "npm_config_user": "",
  "npm_config_userconfig": "C:\\Users\\SAFIULLAH\\.npmrc",
  "npm_config_user_agent": "npm/6.14.6 node/v12.18.3 win32 x64",
  "npm_config_version": "",
  "npm_config_versions": "",
  "npm_config_viewer": "browser",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "start",
  "npm_lifecycle_script": "react-dotenv && react-scripts start",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_browserslist_development_0": "last 1 chrome version",
  "npm_package_browserslist_development_1": "last 1 firefox version",
  "npm_package_browserslist_development_2": "last 1 safari version",
  "npm_package_browserslist_production_0": ">0.2%",
  "npm_package_browserslist_production_1": "not dead",
  "npm_package_browserslist_production_2": "not op_mini all",
  "npm_package_dependencies_axios": "^0.21.1",
  "npm_package_dependencies_chart_js": "^2.9.4",
  "npm_package_dependencies_react": "^17.0.2",
  "npm_package_dependencies_react_chartjs_2": "^2.11.1",
  "npm_package_dependencies_react_dom": "^17.0.2",
  "npm_package_dependencies_react_elastic_carousel": "^0.11.4",
  "npm_package_dependencies_react_redux": "^7.2.3",
  "npm_package_dependencies_react_scripts": "4.0.3",
  "npm_package_dependencies_redux": "^4.0.5",
  "npm_package_dependencies_redux_logger": "^3.0.6",
  "npm_package_dependencies_redux_thunk": "^2.3.0",
  "npm_package_dependencies_styled_components": "^5.2.3",
  "npm_package_dependencies_web_vitals": "^1.1.1",
  "npm_package_dependencies__material_ui_core": "^4.11.3",
  "npm_package_dependencies__material_ui_icons": "^4.11.2",
  "npm_package_dependencies__material_ui_lab": "^4.0.0-alpha.57",
  "npm_package_dependencies__testing_library_jest_dom": "^5.11.10",
  "npm_package_dependencies__testing_library_react": "^11.2.6",
  "npm_package_dependencies__testing_library_user_event": "^12.8.3",
  "npm_package_description": "Preview avalible at https://safithetechi.github.io/weather-app/",
  "npm_package_devDependencies_enzyme": "^3.11.0",
  "npm_package_devDependencies_enzyme_adapter_react_16": "^1.15.6",
  "npm_package_devDependencies_gh_pages": "^3.1.0",
  "npm_package_devDependencies_redux_mock_store": "^1.5.4",
  "npm_package_eslintConfig_extends_0": "react-app",
  "npm_package_eslintConfig_extends_1": "react-app/jest",
  "npm_package_gitHead": "3ec820e2e3bdb21edfe9755c1a56903e8d43ec9f",
  "npm_package_homepage": "http://safithetechi.github.io/weather-app/",
  "npm_package_name": "weather-app",
  "npm_package_private": "true",
  "npm_package_readmeFilename": "README.md",
  "npm_package_scripts_build": "react-dotenv && react-scripts build",
  "npm_package_scripts_deploy": "gh-pages -d build",
  "npm_package_scripts_eject": "react-scripts eject",
  "npm_package_scripts_predeploy": "npm run build",
  "npm_package_scripts_start": "react-dotenv && react-scripts start",
  "npm_package_scripts_test": "react-dotenv && react-scripts test",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "4",
  "OneDrive": "C:\\Users\\SAFIULLAH\\OneDrive",
  "ORIGINAL_PATH": "C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\SAFIULLAH\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY;C:\\Users\\SAFIULLAH\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm;C:\\Users\\SAFIULLAH\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Java\\jdk1.8.0_261\\bin;C:\\Users\\SAFIULLAH\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\SAFIULLAH\\platform-tools_r30.0.5-windows\\platform-tools\\adb.exe;C:\\Program Files\\MongoDB\\Server\\4.4\\bin",
  "ORIGINAL_TEMP": "C:/Users/SAFIUL~1/AppData/Local/Temp",
  "ORIGINAL_TMP": "C:/Users/SAFIUL~1/AppData/Local/Temp",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "PATH": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;E:\\Payoneer\\weather-app\\node_modules\\.bin;C:\\Users\\SAFIULLAH\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\SAFIULLAH\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY;C:\\Users\\SAFIULLAH\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm;C:\\Users\\SAFIULLAH\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Java\\jdk1.8.0_261\\bin;C:\\Users\\SAFIULLAH\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\SAFIULLAH\\platform-tools_r30.0.5-windows\\platform-tools\\adb.exe;C:\\Program Files\\MongoDB\\Server\\4.4\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl",
  "Path": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\npm-lifecycle\\node-gyp-bin;E:\\Payoneer\\weather-app\\node_modules\\.bin;C:\\Users\\SAFIULLAH\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\SAFIULLAH\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\nodejs;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY;C:\\Users\\SAFIULLAH\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\SAFIULLAH\\AppData\\Roaming\\npm;C:\\Users\\SAFIULLAH\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Java\\jdk1.8.0_261\\bin;C:\\Users\\SAFIULLAH\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\SAFIULLAH\\platform-tools_r30.0.5-windows\\platform-tools\\adb.exe;C:\\Program Files\\MongoDB\\Server\\4.4\\bin;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PKG_CONFIG_PATH": "C:\\Program Files\\Git\\mingw64\\lib\\pkgconfig;C:\\Program Files\\Git\\mingw64\\share\\pkgconfig",
  "PLINK_PROTOCOL": "ssh",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 142 Stepping 9, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8e09",
  "ProgramData": "C:\\ProgramData",
  "PROGRAMFILES": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\SAFIULLAH\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "PWD": "E:/Payoneer/weather-app",
  "SESSIONNAME": "Console",
  "SHELL": "C:\\Program Files\\Git\\usr\\bin\\bash.exe",
  "SHLVL": "2",
  "SSH_ASKPASS": "C:/Program Files/Git/mingw64/libexec/git-core/git-gui--askpass",
  "SYSTEMDRIVE": "C:",
  "SYSTEMROOT": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\SAFIUL~1\\AppData\\Local\\Temp",
  "TERM": "xterm",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.55.2",
  "TMP": "C:\\Users\\SAFIUL~1\\AppData\\Local\\Temp",
  "TMPDIR": "C:\\Users\\SAFIUL~1\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-FKHOGE5",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-FKHOGE5",
  "USERNAME": "SAFIULLAH",
  "USERPROFILE": "C:\\Users\\SAFIULLAH",
  "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox\\",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\SAFIULLAH\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\SAFIULLAH\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-dde932b5e0-sock",
  "WINDIR": "C:\\WINDOWS",
  "_": "C:/Users/SAFIULLAH/AppData/Local/Programs/Microsoft VS Code/Code.exe",
  "_prog": "node"
};